name: github pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'      

      - run: yarn install
      
      - name: Build
        run: yarn build
        with:
          BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}        

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out          
          cname: zedlen.com          